### ISSUE TITLE
Separate StatusCode network exceptions

### ISSUE THREAD

**Issue by stone-w4tch3r** [ArbusBiz/Arbus.Network#11]
![arbus network error](https://user-images.githubusercontent.com/100294019/191992227-ed475961-b2de-4bb4-b9e1-24c2a2bca5b7.png)
Expected NetworkException to be only for errors connected with work of network, such as timeout, network loss and so on

**Comment by evgenyvalavin** [comment]
I'm not quite understood what you're trying to say. 
An instance of NetworkExpection has a StatusCode property. InternalServerError is one of the standard HttpStatusCodes. Doesn't seem wrong to me

**Comment by evgenyvalavin** [comment]
The initial idea is to separate status code exceptions and non status code exceptions (response wasn't received). ResponseNetworkException is an example

**Comment by evgenyvalavin** [comment]
#44 
A lot of exceptions were removed. I believe there's no need for the current task.
