### ISSUE TITLE
Add image content types to HttpCotentType

### ISSUE THREAD

**Issue by evgenyvalavin** [ArbusBiz/Arbus.Network#32]
https://www.geeksforgeeks.org/http-headers-content-type/
![image](https://github.com/ArbusBiz/Arbus.Network/assets/35497422/b45f0b2a-1f16-414c-893e-68947338f273)

**Comment by evgenyvalavin** [comment]
@Leo506 do you think will we need it in the Waiter project?

**Comment by Leo506** [comment]
Honestly I don't know. But I think it could help determine image type for correct deserialization from bytes array (if it will be necessary)

**Comment by Leo506** [comment]
Anyway, if we add these header values we won't lose anything

**Comment by evgenyvalavin** [comment]
Fine. Wait until the real need
